/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Peripherals v4.1
processor: MK64FX512xxx12
package_id: MK64FX512VMD12
mcu_data: ksdk2_0
processor_version: 4.0.1
functionalGroups:
- name: BOARD_InitPeripherals
  called_from_default_init: true
  selectedCore: core0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'system'
- type_id: 'system_54b53072540eeeb8f8e9343e71f28176'
- global_system_definitions: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "peripherals.h"

uint32_t g_rxFifoFilters[] = {
    FLEXCAN_RX_FIFO_STD_FILTER_TYPE_A(0x00, 0, 0),
    FLEXCAN_RX_FIFO_STD_FILTER_TYPE_A(0x01, 0, 0),
    FLEXCAN_RX_FIFO_STD_FILTER_TYPE_A(0x02, 0, 0),
    FLEXCAN_RX_FIFO_STD_FILTER_TYPE_A(0x03, 0, 0)
};

/***********************************************************************************************************************
 * BOARD_InitPeripherals functional group
 **********************************************************************************************************************/
/***********************************************************************************************************************
 * FlexCAN_1 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'FlexCAN_1'
- type: 'flexcan'
- mode: 'interrupts'
- type_id: 'flexcan_ba45456ec815807245205237e2bf425b'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'CAN0'
- config_sets:
  - interruptsCfg:
    - messageBufferIrqs: '0'
    - interruptsEnable: ''
    - enable_ored_mb_irq: 'false'
    - interrupt_ored_mb:
      - IRQn: 'CAN0_ORed_Message_buffer_IRQn'
      - enable_priority: 'false'
      - enable_custom_name: 'false'
    - enable_busoff_irq: 'false'
    - interrupt_busoff:
      - IRQn: 'CAN0_Bus_Off_IRQn'
      - enable_priority: 'false'
      - enable_custom_name: 'false'
    - enable_error_irq: 'false'
    - interrupt_error:
      - IRQn: 'CAN0_Error_IRQn'
      - enable_priority: 'false'
      - enable_custom_name: 'false'
    - enable_tx_irq: 'false'
    - interrupt_tx:
      - IRQn: 'CAN0_Tx_Warning_IRQn'
      - enable_priority: 'false'
      - enable_custom_name: 'false'
    - enable_rx_irq: 'false'
    - interrupt_rx:
      - IRQn: 'CAN0_Rx_Warning_IRQn'
      - enable_priority: 'false'
      - enable_custom_name: 'false'
    - enable_wakeup_irq: 'false'
    - interrupt_wakeup:
      - IRQn: 'CAN0_Wake_Up_IRQn'
      - enable_priority: 'false'
      - enable_custom_name: 'false'
  - fsl_flexcan:
    - can_config:
      - clockSource: 'kFLEXCAN_ClkSrcOsc'
      - clockSourceFreq: 'BOARD_BootClockRUN'
      - baudRate: '500000'
      - maxMbNum: '16'
      - enableLoopBack: 'false'
      - enableSelfWakeup: 'false'
      - enableIndividMask: 'false'
      - timingConfig:
        - propSeg: '2'
        - phaseSeg1: '4'
        - phaseSeg2: '3'
        - rJumpwidth: '2'
        - bitTime: []
    - enableRxFIFO: 'true'
    - rxFIFO:
      - idFilterTable: 'g_flexcanRxFilters'
      - idFilterNum: 'num0'
      - idFilterType: 'kFLEXCAN_RxFifoFilterTypeA'
      - priority: 'kFLEXCAN_RxFifoPrioHigh'
    - channels:
      - 0:
        - mbID: '9'
        - mbType: 'mbRx'
        - rxMb:
          - id: '0'
          - format: 'kFLEXCAN_FrameFormatStandard'
          - type: 'kFLEXCAN_FrameTypeData'
      - 1:
        - mbID: '8'
        - mbType: 'mbTx'
        - rxMb:
          - id: '0'
          - format: 'kFLEXCAN_FrameFormatStandard'
          - type: 'kFLEXCAN_FrameTypeData'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const flexcan_config_t FlexCAN_1_config = {
  .clkSrc = kFLEXCAN_ClkSrcOsc,
  .baudRate = 500000,
  .maxMbNum = 16,
  .enableLoopBack = false,
  .enableSelfWakeup = false,
  .enableIndividMask = false,
  .timingConfig = {
    .propSeg = 1,
    .phaseSeg1 = 3,
    .phaseSeg2 = 2,
    .rJumpwidth = 1
  }
};
/* Message buffer 9 configuration structure */
const flexcan_rx_mb_config_t FlexCAN_1_rx_mb_config_9 = {
  .id = 0x00,
  .format = kFLEXCAN_FrameFormatStandard,
  .type = kFLEXCAN_FrameTypeData
};
flexcan_rx_fifo_config_t FlexCAN_1_rx_fifo_config = {
  .idFilterNum = 0,
  .idFilterType = kFLEXCAN_RxFifoFilterTypeA,
  .priority = kFLEXCAN_RxFifoPrioLow
};

void FlexCAN_1_init(void) {
  FLEXCAN_Init(FLEXCAN_1_PERIPHERAL, &FlexCAN_1_config, FLEXCAN_1_CLOCK_SOURCE);

  FLEXCAN_SetRxFifoGlobalMask(FLEXCAN_1_PERIPHERAL, 0x03);
  FlexCAN_1_rx_fifo_config.idFilterTable = g_rxFifoFilters;
  FlexCAN_1_rx_fifo_config.idFilterNum = sizeof(g_rxFifoFilters) / sizeof(g_rxFifoFilters[0]);
  FLEXCAN_SetRxFifoConfig(FLEXCAN_1_PERIPHERAL, &FlexCAN_1_rx_fifo_config, true);

  /* Message buffer 9 initialization */
  FLEXCAN_SetRxMbConfig(FLEXCAN_1_PERIPHERAL, 9, &FlexCAN_1_rx_mb_config_9, true);
  FLEXCAN_SetRxMbGlobalMask(FLEXCAN_1_PERIPHERAL, 0x00);
  /* Message buffer 8 initialization */
  FLEXCAN_SetTxMbConfig(FLEXCAN_1_PERIPHERAL, 8, true);
}

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/
void BOARD_InitPeripherals(void)
{
  /* Initialize components */
  FlexCAN_1_init();
}

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void)
{
  BOARD_InitPeripherals();
}
